import type { Project } from "./types";

/** Placeholder projects. Copy, imagery and sections are to be replaced. */
export const projects: Project[] = [
  {
    slug: "neo-advance",
    image: { src: "/placeholders/neo-advance.svg", alt: "", width: 1600, height: 1200 },
    scene: "neo-advance",
    title: "Neo Advance",
    description: "Connecting banking, credit, and progression into one experience",
    tags: ["fintech", "insights-analytics"],
    summary: "Placeholder summary. One or two sentences on the problem, your role and why the work mattered.",
    meta: ["Fintech", "0→1"],
    year: "20XX",
    status: "placeholder",
    sections: [
      { id: "context", title: "Context" },
      { id: "framing", title: "Framing the problem" },
      { id: "concept", title: "From concept to product" },
      { id: "outcome", title: "Outcome" },
    ],
  },
  {
    slug: "mutexa",
    image: { src: "/placeholders/ai-experimental.svg", alt: "", width: 1920, height: 1080 },
    scene: "mutexa",
    title: "MutexaHTP",
    description: "Designing human–AI collaboration for enzyme research",
    tags: ["ai", "b2b-saas"],
    summary: "Placeholder summary. A home for explorations, prototypes and AI-native product thinking.",
    meta: ["AI", "B2B SaaS"],
    year: "20XX",
    status: "placeholder",
    sections: [
      { id: "context", title: "Context" },
      { id: "explorations", title: "Explorations" },
      { id: "principles", title: "Principles" },
    ],
  },
  {
    slug: "reimagining-analytics",
    image: { src: "/placeholders/banking-platform.svg", alt: "", width: 1200, height: 1500 },
    scene: "beacon-analytics",
    title: "Reimagining Analytics",
    description: "Boosting business metrics by revamping the design system",
    tags: ["insights-analytics", "design-system"],
    summary: "Placeholder summary.",
    meta: ["Insights & Analytics", "Design system"],
    year: "20XX",
    status: "placeholder",
    sections: [{ id: "context", title: "Context" }],
  },
  {
    slug: "brightcove-beacon",
    image: { src: "/placeholders/banking-platform.svg", alt: "", width: 1200, height: 1500 },
    scene: "brightcove",
    title: "Brightcove Beacon",
    description: "Taming complexity in an enterprise content management system",
    tags: ["b2b-saas", "design-system"],
    summary: "Placeholder summary. Describe the platform, the journeys it covered and the scope of your leadership.",
    meta: ["B2B SaaS", "Design system"],
    year: "20XX",
    status: "placeholder",
    sections: [
      { id: "context", title: "Context" },
      { id: "system", title: "A shared system" },
      { id: "governance", title: "Adoption and governance" },
      { id: "outcome", title: "Outcome" },
    ],
  },
];
